name: Run snip_to_pdf (demo)

on:
  workflow_dispatch:   # lets you trigger it manually from the GitHub UI

jobs:
  run-snip:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Tesseract
        run: choco install tesseract --no-progress

      - name: Run script (non‑interactive demo)
        run: |
          echo "Skipping interactive snip – just checking OCR works on a sample image."
          python -c "from src.ocr import image_to_text; from PIL import Image; img=Image.new('RGB',(200,50),color='white'); img.save('sample.png'); print(image_to_text(img))"
